export default function ProclamationLead() {
  return (
    <section className="py-24 lg:py-32 border-b border-neon/15">
      <div className="max-w-3xl mx-auto px-6 lg:px-12 font-inter text-[18px] lg:text-xl leading-[1.7] text-white space-y-8">
        <p>
          The factory floor has moved upstream. The people who used to cut,
          sew, mold, and pack your product are now running their own brands,
          their own ads, their own livestreams, their own warehouses. They
          have the cost base. They have the speed.{" "}
          <strong className="text-neon font-semibold">
            And now they have the customer.
          </strong>
        </p>

        <p>
          Automotive saw it first. BYD did not become the largest EV maker in
          the world by selling to Tesla. They went direct - vertical, fast,
          integrated - and the legacy brands found themselves competing
          against their own former suppliers. Fashion and beauty sit on the
          same timeline.
        </p>

        <p>
          Your last advantage was execution. Better ads. Better creative.
          Better landing pages. That advantage is being neutralized in real
          time. UGC is generated by AI in minutes. Product photography no
          longer needs a studio. The gap between a $20M brand&apos;s marketing
          and a factory-direct competitor&apos;s marketing is closing by the
          quarter.
        </p>

        <p>
          If running good ads is your only moat, you are running on borrowed
          time. The brands that survive the next 24 months will not be the
          ones with the sharpest creative team. They will be the ones with
          something that cannot be cloned:{" "}
          <strong className="text-white font-semibold">
            a defined identity, a community that buys regardless of ad
            performance, vertical control over supply, and the speed to act
            before the market does.
          </strong>
        </p>

        <p className="font-space font-bold text-2xl lg:text-3xl text-neon leading-[1.3] pt-4">
          On this session, I&apos;ll show you where the new moats are forming -
          and what your brand needs to own now to be on the right side of the
          shift.
        </p>
      </div>
    </section>
  );
}
